apiVersion: v1
kind: Service
metadata:
  name: ifactorial
  labels:
    run: ifactorial
spec:
  ports:
    - name: default
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    run: ifactorial
#  type: LoadBalancer
