apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ifactorial
spec:
  selector:
    matchLabels:
      run: ifactorial
  replicas: 2
  template:
    metadata:
      labels:
        run: ifactorial
    spec:
      containers:
        - name: ifactorial
          image: ifactorial:0.5
          ports:
            - containerPort: 9090
